spring:
  datasource:
    url: jdbc:postgresql://postgres-task:5432/taskdb
    username: task
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true